### ISSUE TITLE
HTTP流量转发失败

### ISSUE THREAD

**Issue by spark135246** [liberal-boy/tls-shunt-proxy#14]
分流器配置文件
```yaml
listen: 0.0.0.0:443
redirecthttps: 0.0.0.0:80

vhosts:
  - name: 域名
    tlsoffloading: true
    managedcert: true
    keytype: p256
    alpn: h2,http/1.1
    protocols: tls12,tls13
    http:
      handler: proxyPass
      args: 127.0.0.1:5212
    default:
      handler: proxyPass
      args: unix:/tmp/v2ray-ds/v2ray.sock
```

目的主要是用来分流tcp和http流量，下面是日志

![日志](https://user-images.githubusercontent.com/26293439/89277160-0a457d80-d677-11ea-9601-9f0502cd7581.png)

使用tcp代理的时候正常转发，但是访问网站就出问题了，直接访问网站5212端口网站正常显示。

下面是网站的开源地址 [Cloudreve](https://github.com/cloudreve/Cloudreve)
