### ISSUE TITLE
更新到0.4.0版本后，部分vhost无法正常转发

### ISSUE THREAD

**Issue by tufu9441** [liberal-boy/tls-shunt-proxy#2]
RT，配置文件如下，更新到0.4.0版本后，第1个vhost可以正常分流转发，后2个就失效了；退回到0.3.1版本后又能恢复正常。
```
# listen: 监听地址
listen: 0.0.0.0:443

# vhosts: 按照按照 tls sni 扩展划分为多个虚拟 host
vhosts:

    # name 对应 tls sni 扩展的 server name
  - name: v2cn.win

    # tlsoffloading: 解开 tls，true 为解开，解开后可以识别 http 流量，适用于 vmess over tls 和 http over tls (https) 分流等
    tlsoffloading: true

    # managedcert: 管理证书，开启后将自动从 LetsEncrypt 获取证书，根据 LetsEncrypt 的要求，必须监听 443 端口才能签发
    # 开启时 cert 和 key 设置的证书无效，关闭时将使用 cert 和 key 设置的证书
    managedcert: false

    # cert: tls 证书路径，
    cert: /usr/local/caddy/v2cn.win.crt

    # key: tls 私钥路径
    key: /usr/local/caddy/v2cn.win.key

    # http: 识别出的 http 流量的处理方式
    http:

      # handler: fileServer 将服务一个静态网站
      handler: proxyPass

      # args: 静态网站的文件路径
      args: 127.0.0.1:8081

    # default: 其他流量处理方式
    default:

      # handler: proxyPass 将流量转发至另一个地址
      handler: proxyPass

      # args: 转发的目标地址
      args: 127.0.0.1:9441

      # args: 也可以使用 domain socket
      # args: unix:/path/to/ds/file

  - name: router.v2cn.win

    tlsoffloading: true

    managedcert: false

    cert: /usr/local/caddy/v2cn.win.crt

    key: /usr/local/caddy/v2cn.win.key

    default:

      handler: proxyPass

      args: 127.0.0.1:8082

  - name: disqus.haomwei.com

    tlsoffloading: true

    managedcert: false

    cert: /usr/local/caddy/haomwei.com.crt

    key: /usr/local/caddy/haomwei.com.key

    default:

      handler: proxyPass

      args: 127.0.0.1:8083
```
